name: quickstep_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.24.5"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  salomon_bottom_bar: ^3.3.1
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  geolocator: ^10.1.0
  flutter_background_service: ^5.0.5
  flutter_blue_plus: ^1.34.5
  ble_peripheral: ^2.4.0
  permission_handler: ^11.3.1
  supabase_flutter: ^2.5.4
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.9.3
  badges: ^3.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timeago: ^3.4.0
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  get: ^4.6.5
  socket_io_client: ^2.0.1
  dio: ^5.0.1
  loading_animation_widget: ^1.2.0+4
  flutter_dotenv: ^5.0.2
  screenshot: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.17
  flutter_blue_plus_android: 3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/dotenv/
